export const genres = [
  'Action and Adventure',
  'Anthology',
  'Art',
  'Autobiography',
  'Biography',
  'Chick Lit',
  'Childrens',
  'Classic',
  'Comic/Graphic Novel',
  'Crime',
  'Detective',
  'Drama',
  'Fable',
  'Fairy Tale',
  'Fantasy',
  'Historical Fiction',
  'Horror',
  'Humor',
  'Journal',
  'Literary Fiction',
  'Mystery',
  'Mythology',
  'Paranormal Romance',
  'Philosophical',
  'Poetry',
  'Political',
  'Romance',
  'Satire',
  'Science Fiction',
  'Short Story',
  'Suspense/Thriller',
  'Self-help',
  'Spiritual',
  'Sports',
  'Travel',
  'True Crime',
  'Western',
  'Young Adult (YA)',
  'Dystopian',
  'Steampunk',
  'Bildungsroman',
  'Realistic Fiction',
  'High Fantasy',
  'Low Fantasy',
  'Urban Fantasy',
  'Magic Realism',
  'Space Opera',
  'Superhero',
  'Sword and Sorcery',
  'Gothic Fiction'
]

export default genres
