export const genres = [
  'Action and Adventure',
  'Adventure',
  'Alternate History',
  'Anthology',
  'Art',
  'Autobiography',
  'Biography',
  'Childrens',
  'Classic',
  'Comic/Graphic Novel',
  'Contemporary',
  'Crime',
  'Drama',
  'Dystopian',
  'Epic',
  'Erotic Fiction',
  'Fable',
  'Fairy Tale',
  'Fantasy',
  'Gothic Fiction',
  'Historical Fiction',
  'Horror',
  'Humor',
  'Inspirational',
  'Journal',
  'LGBT',
  'Literary Fiction',
  'Military/War Fiction',
  'Mystery',
  'Mythology',
  'Noir',
  'Paranormal Romance',
  'Philosophical',
  'Poetry',
  'Political',
  'Post-Apocalyptic',
  'Psychological Thriller',
  'Religious',
  'Romance',
  'Satire',
  'Science Fiction',
  'Self-help',
  'Short Story',
  'Speculative Fiction',
  'Spiritual',
  'Sports',
  'Suspense/Thriller',
  'Travel',
  'True Crime',
  'Western',
  'Young Adult (YA)'
]
export default genres
